application:
  title: "夏律师的网站"

spring:
  datasource:
    url: "jdbc:sqlite:/workspace/boot.db"
    username:
    passoword:
    driver-class-name: "org.sqlite.JDBC"
  jpa:
    database-platform: com.SQLiteDialect
    properties:
      hibernate:
        hbm2ddl:
          auto: update
    hibernate:
      ddl-auto: update